# Generated by Django 5.0.1 on 2024-01-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
        ("unit_of_measurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="unit_of_measurement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="unit_of_measurement.unitofmeasurement",
            ),
            preserve_default=False,
        ),
    ]
