# Generated by Django 5.0.1 on 2024-01-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
        ("item_stock_info", "0001_initial"),
        ("item_type", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_stock_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_item",
                to="item_stock_info.itemstockinfo",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="item_type.itemtype",
            ),
        ),
    ]
