# Generated by Django 5.0.1 on 2024-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_item_unit_of_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
