# Generated by Django 5.0.1 on 2024-01-20 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="item_stock_info",
        ),
    ]
