# Generated by Django 5.0.1 on 2024-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_item_item_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
