# Generated by Django 5.0.1 on 2024-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="abbreviation",
            field=models.CharField(max_length=4),
        ),
    ]
