# Generated by Django 5.0.1 on 2024-02-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_alter_person_contact_no"),
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="patient_name",
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="person.person",
            ),
            preserve_default=False,
        ),
    ]
