# Generated by Django 5.0.1 on 2024-04-18 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_alter_itembatch_description"),
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineDosageElement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.IntegerField()),
                ("dayMedSchedule", models.CharField(max_length=255)),
                ("medicineTiming", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="prescribedmedicine",
            name="dosage",
        ),
        migrations.CreateModel(
            name="MedicineDosage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("duration_value", models.IntegerField(blank=True, null=True)),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("next_visit", "Until Next Visit"),
                            ("other", "Other"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("medicine", models.ManyToManyField(to="item.item")),
                (
                    "medicines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medicine_dosage",
                        to="item.item",
                    ),
                ),
                (
                    "dosage_elements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="medicine_dosages",
                        to="prescription.medicinedosageelement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prescribedmedicine",
            name="dosage",
            field=models.ManyToManyField(to="prescription.medicinedosage"),
        ),
    ]
