# Generated by Django 5.0.1 on 2024-04-19 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescriptionitem",
            old_name="dosage",
            new_name="dosages",
        ),
    ]
