# Generated by Django 5.0.1 on 2024-04-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_alter_itembatch_description"),
        ("prescription", "0002_medicinedosageelement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinedosage",
            name="dosage_elements",
        ),
        migrations.RemoveField(
            model_name="medicinedosage",
            name="medicines",
        ),
        migrations.RemoveField(
            model_name="prescribedmedicine",
            name="dosage",
        ),
        migrations.AddField(
            model_name="medicinedosage",
            name="prescribedMedicine",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="prescription.prescribedmedicine",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicinedosageelement",
            name="medicine_dosage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="prescription.medicinedosage",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="medicinedosage",
            name="medicine",
        ),
        migrations.AddField(
            model_name="medicinedosage",
            name="medicine",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="medicine_dosage",
                to="item.item",
            ),
            preserve_default=False,
        ),
    ]
