# Generated by Django 5.0.1 on 2024-02-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_alter_person_contact_no"),
        ("prescription", "0002_remove_prescription_patient_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor_name",
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_doctor",
                to="person.person",
            ),
            preserve_default=False,
        ),
    ]
