# Generated by Django 5.0.1 on 2024-04-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0002_rename_dosage_prescriptionitem_dosages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionitem",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescribed_item_set",
                to="prescription.prescription",
            ),
        ),
    ]
