# Generated by Django 5.0.1 on 2024-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0003_remove_prescription_doctor_name_prescription_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescribedmedicine",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
