# Generated by Django 5.0.1 on 2024-04-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0003_alter_prescriptionitem_prescription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="name",
        ),
        migrations.AddField(
            model_name="prescription",
            name="advice_and_instructions",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="chief_complaints",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
