# Generated by Django 5.0.1 on 2024-04-18 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0003_remove_medicinedosage_dosage_elements_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescribedmedicine",
            name="name",
        ),
    ]
