# Generated by Django 5.0.1 on 2024-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0004_remove_prescribedmedicine_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescribedmedicine",
            old_name="item",
            new_name="medicine",
        ),
    ]
