# Generated by Django 5.0.1 on 2024-04-22 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0004_remove_prescriptionitem_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescriptionitem",
            old_name="item",
            new_name="medicine",
        ),
    ]
