# Generated by Django 5.0.1 on 2024-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0004_prescribedmedicine_active_prescription_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescribedmedicine",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="active",
            new_name="is_active",
        ),
    ]
