# Generated by Django 5.0.1 on 2024-05-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "__first__"),
        ("prescription", "0005_rename_item_prescriptionitem_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_patient",
                to="patient.patient",
            ),
        ),
    ]
