# Generated by Django 5.0.1 on 2024-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0005_rename_active_prescribedmedicine_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_date",
            field=models.DateTimeField(),
        ),
    ]
