# Generated by Django 5.0.1 on 2024-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0005_rename_item_prescriptionitem_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
