# Generated by Django 5.0.1 on 2024-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0005_rename_item_prescribedmedicine_medicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="advice_and_instructions",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="chief_complaint",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
