# Generated by Django 5.0.1 on 2024-02-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0006_alter_prescription_prescription_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescribedmedicine",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescribed_medicine_set",
                to="prescription.prescription",
            ),
        ),
    ]
