# Generated by Django 5.0.1 on 2024-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0007_alter_prescribedmedicine_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="code",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
