# Generated by Django 5.0.1 on 2024-02-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0006_remove_department_active_remove_person_active_and_more"),
        ("prescription", "0008_prescription_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ManyToManyField(
                related_name="prescriptions_doctor", to="person.person"
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ManyToManyField(
                related_name="prescriptions_patient", to="person.person"
            ),
        ),
    ]
