# Generated by Django 5.0.1 on 2024-02-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0006_remove_department_active_remove_person_active_and_more"),
        ("prescription", "0009_remove_prescription_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.AddField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_doctor",
                to="person.person",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_patient",
                to="person.person",
            ),
            preserve_default=False,
        ),
    ]
