# Generated by Django 5.0.1 on 2024-02-16 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescription", "0010_remove_prescription_doctor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="prescription_date",
            new_name="date_and_time",
        ),
    ]
