# Generated by Django 5.0.1 on 2024-05-09 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0006_delete_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("mzu_hc_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "patient_type",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("Employee Dependent", "Employee Dependent"),
                            ("Student", "Student"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("mzu_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("illness", models.JSONField(blank=True, default=list, null=True)),
                ("allergy", models.JSONField(blank=True, default=list, null=True)),
                (
                    "mzu_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="person.person",
                    ),
                ),
            ],
        ),
    ]
