# Generated by Django 5.0.1 on 2024-05-21 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mzu_hc_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "patient_type",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("Employee Dependent", "Employee Dependent"),
                            ("Student", "Student"),
                            ("MZU_outsider", "MZU_outsider"),
                        ],
                        max_length=255,
                    ),
                ),
                ("illness", models.JSONField(blank=True, default=list, null=True)),
                ("allergy", models.JSONField(blank=True, default=list, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="person.employee",
                    ),
                ),
                (
                    "employee_dependent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="person.employeedependent",
                    ),
                ),
                (
                    "mzu_outsider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="person.mzuoutsider",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="person.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
