# Generated by Django 5.0.1 on 2024-05-09 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="mzu_id",
            new_name="student_id",
        ),
    ]
