# Generated by Django 5.0.1 on 2024-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_rename_mzu_id_patient_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="patient",
            name="year_of_birth",
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
