# Generated by Django 5.0.1 on 2024-05-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_rename_student_id_patient_mzu_student_id_and_more"),
        ("person", "0008_employee_student_user_delete_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="person.employee",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="employee_dependent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="person.employeedependent",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="person.student",
            ),
        ),
    ]
