# Generated by Django 5.0.1 on 2024-05-27 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineDosage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("duration_value", models.IntegerField(blank=True, null=True)),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("next_visit", "Until Next Visit"),
                            ("other", "Other"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_dosage",
                        to="item.item",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicineDosageTiming",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity_in_one_take", models.IntegerField()),
                ("day_med_schedule", models.CharField(max_length=255)),
                ("medicine_timing", models.CharField(max_length=255)),
                (
                    "medicine_dosage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_dosage_timing_set",
                        to="medicine.medicinedosage",
                    ),
                ),
            ],
        ),
    ]
