# Generated by Django 5.0.1 on 2024-02-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineDosage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity_in_one_take", models.IntegerField()),
                ("how_many_times_in_a_day", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dosages",
                        to="item.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineDosageDuration",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("days", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "medicine_dosage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="durations",
                        to="medicine.medicinedosage",
                    ),
                ),
            ],
        ),
    ]
