# Generated by Django 5.0.1 on 2024-02-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinedosageduration",
            name="medicine_dosage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medicine.medicinedosage",
            ),
        ),
    ]
