# Generated by Django 5.0.1 on 2024-04-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinedosagetiming",
            name="medicine_dosage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine_dosage_timing_set",
                to="medicine.medicinedosage",
            ),
        ),
    ]
