# Generated by Django 5.0.1 on 2024-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0002_alter_medicinedosageduration_medicine_dosage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinedosage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="medicinedosageduration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
