# Generated by Django 5.0.1 on 2024-04-19 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicine", "0002_alter_medicinedosagetiming_medicine_dosage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicinedosagetiming",
            old_name="dayMedSchedule",
            new_name="day_med_schedule",
        ),
        migrations.RenameField(
            model_name="medicinedosagetiming",
            old_name="medicineTiming",
            new_name="medicine_timing",
        ),
    ]
