# Generated by Django 5.0.1 on 2024-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "medicine",
            "0003_rename_daymedschedule_medicinedosagetiming_day_med_schedule_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicinedosage",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
