# Generated by Django 5.0.1 on 2024-01-23 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineDosage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_in_one_take", models.IntegerField()),
                ("how_many_times_in_a_day", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dosages",
                        to="item.item",
                    ),
                ),
            ],
        ),
    ]
