# Generated by Django 5.0.1 on 2024-01-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("id_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idmanager",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
