# Generated by Django 5.0.1 on 2024-01-25 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("id_manager", "0003_idmanager_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idmanager",
            name="description",
        ),
        migrations.RemoveField(
            model_name="idmanager",
            name="name",
        ),
    ]
