# Generated by Django 5.0.1 on 2024-01-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemStockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="item.item",
                    ),
                ),
            ],
        ),
    ]
