# Generated by Django 5.0.1 on 2024-01-20 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_remove_item_item_stock_info"),
        ("item_stock_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemstockinfo",
            name="item",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="item.item"
            ),
            preserve_default=False,
        ),
    ]
