# Generated by Django 5.0.1 on 2024-02-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="abbreviation",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
