# Generated by Django 5.0.1 on 2024-01-26 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0002_alter_supplier_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplier",
            old_name="contact",
            new_name="contact_no",
        ),
    ]
