# Generated by Django 5.0.1 on 2024-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0003_alter_supplier_address_alter_supplier_contact_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="contact_no",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
