# Generated by Django 5.0.1 on 2024-01-29 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0003_rename_contact_supplier_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
