# Generated by Django 5.0.1 on 2024-01-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0004_alter_supplier_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
