# Generated by Django 5.0.1 on 2024-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indent_transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indentinventorytransaction",
            name="supply_order_no",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
