# Generated by Django 5.0.1 on 2024-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dispense_transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispenseinventorytransaction",
            name="pharmacist",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
