# Generated by Django 5.0.1 on 2024-02-18 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dispense_transaction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispenseinventorytransaction",
            name="dispense_date",
        ),
    ]
