# Generated by Django 5.0.1 on 2024-06-24 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organisation_unit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MZUOutsider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor "),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("mobile_no", models.PositiveBigIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255)),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("Teaching", "Teaching"),
                            ("Non-Teaching", "Non-Teaching"),
                        ],
                        max_length=255,
                    ),
                ),
                ("mzu_employee_id", models.CharField(max_length=255, unique=True)),
                ("designation", models.CharField(max_length=255)),
                (
                    "organisation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_organization_unit",
                        to="organisation_unit.organisationunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDependent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mzu_employee_dependent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("relation", models.CharField(max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_dependents",
                        to="person.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("mobile_no", models.PositiveBigIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("mzu_student_id", models.CharField(max_length=255, unique=True)),
                ("programme", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "year_of_admission",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "organisation_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_organization_unit",
                        to="organisation_unit.organisationunit",
                    ),
                ),
            ],
        ),
    ]
