# Generated by Django 5.0.1 on 2024-04-03 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="department",
        ),
    ]
