# Generated by Django 5.0.1 on 2024-02-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
