# Generated by Django 5.0.1 on 2024-02-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_alter_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="contact_no",
            field=models.PositiveBigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
