# Generated by Django 5.0.1 on 2024-04-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_alter_person_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
