# Generated by Django 5.0.1 on 2024-02-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0003_person_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="contact_no",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
