# Generated by Django 5.0.1 on 2024-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_alter_person_contact_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="persontype",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
