# Generated by Django 5.0.1 on 2024-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_patient_person_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
