# Generated by Django 5.0.1 on 2024-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0004_alter_person_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
