# Generated by Django 5.0.1 on 2024-05-09 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0005_person_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
