# Generated by Django 5.0.1 on 2024-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0005_department_active_person_active_persontype_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="active",
        ),
        migrations.RemoveField(
            model_name="person",
            name="active",
        ),
        migrations.RemoveField(
            model_name="persontype",
            name="active",
        ),
    ]
