# Generated by Django 5.0.1 on 2024-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0006_person_designation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="contact_no",
        ),
        migrations.AddField(
            model_name="person",
            name="mobile_no",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
