# Generated by Django 5.0.1 on 2024-05-10 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0007_alter_person_gender_alter_person_person_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile_no", models.PositiveBigIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255)),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("Employee Dependent", "Employee Dependent"),
                            ("Student", "Student"),
                        ],
                        max_length=255,
                    ),
                ),
                ("mzu_employee_id", models.CharField(max_length=255, unique=True)),
                ("designation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("mobile_no", models.PositiveBigIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("mzu_student_id", models.CharField(max_length=255, unique=True)),
                ("department", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor "),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.RemoveField(
            model_name="employeedependent",
            name="person",
        ),
        migrations.DeleteModel(
            name="PersonType",
        ),
        migrations.AddField(
            model_name="employeedependent",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="person.employee",
            ),
            preserve_default=False,
        ),
    ]
