# Generated by Django 5.0.1 on 2024-05-10 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0005_patient_employee_patient_employee_dependent_and_more"),
        ("person", "0008_employee_student_user_delete_department_and_more"),
        ("prescription", "0007_alter_prescription_doctor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
