# Generated by Django 5.0.1 on 2024-05-10 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0009_delete_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedependent",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_dependents",
                to="person.employee",
            ),
        ),
    ]
