# Generated by Django 5.0.1 on 2024-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_consumable",
            field=models.BooleanField(default=False),
        ),
    ]
