# Generated by Django 5.0.1 on 2024-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="medicine_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
