# Generated by Django 5.0.1 on 2024-04-24 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_item_medicine_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="medicine_content",
            new_name="cotents",
        ),
    ]
