# Generated by Django 5.0.1 on 2024-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_item_is_consumable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itembatch",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
