# Generated by Django 5.0.1 on 2024-04-24 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_rename_medicine_content_item_cotents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="cotents",
            new_name="contents",
        ),
    ]
