# Generated by Django 5.0.1 on 2024-02-10 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0005_itemstockinfo_inventory_transaction_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemStockInfo",
        ),
    ]
