# Generated by Django 5.0.1 on 2024-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0006_delete_itemstockinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
