# Generated by Django 5.0.1 on 2024-01-23 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0003_remove_item_item_stock_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineDosageDuration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("days", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="item.item",
                    ),
                ),
            ],
        ),
    ]
