# Generated by Django 5.0.1 on 2024-01-20 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicineDosageDuration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("days", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
