# Generated by Django 5.0.1 on 2024-02-06 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0005_issueiteminventorytransaction_item_receiver_and_more",
        ),
        ("organisation_section", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganisactionSection",
            new_name="OrganisationSection",
        ),
    ]
