# Generated by Django 5.0.1 on 2024-02-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organisation_section",
            "0002_rename_organisactionsection_organisationsection",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsection",
            name="code",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
