# Generated by Django 5.0.1 on 2024-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisation_section", "0003_organisationsection_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationsection",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
