# Generated by Django 5.0.1 on 2024-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisation_section", "0004_organisationsection_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisationsection",
            name="active",
        ),
    ]
