# Generated by Django 5.0.1 on 2024-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
