# Generated by Django 5.0.1 on 2024-01-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item_batch", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("dispense", "Dispense"),
                            ("dispose", "Dispose"),
                            ("itemReturnToSupplier", "ItemReturnToSupplier"),
                            ("itemIssue", "ItemIssue"),
                            ("itemIssueReturn", "ItemIssueReturn"),
                            (
                                "itemturnReplacementFromSupplier",
                                "ItemturnReplacementFromSupplier",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                ("remarks", models.CharField(max_length=200, unique=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "item_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_batch.itembatch",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_transaction.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndentTransaction",
            fields=[
                (
                    "transaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="inventory_transaction.transaction",
                    ),
                ),
                ("requested_quantity", models.IntegerField(blank=True, null=True)),
                ("supplyOrderNo", models.CharField(max_length=20, unique=True)),
                ("supplyOrderDate", models.DateField()),
                ("dateOfDeliverty", models.DateField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                    ),
                ),
            ],
            bases=("inventory_transaction.transaction",),
        ),
    ]
