# Generated by Django 5.0.1 on 2024-02-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item_batch", "0001_initial"),
        ("supplier", "0005_alter_supplier_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "inventory_transaction_id",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "inventory_transaction_type",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("dispense", "Dispense"),
                            ("dispose", "Dispose"),
                            ("itemReturnToSupplier", "ItemReturnToSupplier"),
                            ("itemIssue", "ItemIssue"),
                            ("itemIssueReturn", "ItemIssueReturn"),
                            (
                                "itemturnReplacementFromSupplier",
                                "ItemturnReplacementFromSupplier",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "inventory_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventorytransactionitem_set",
                        to="inventory_transaction.inventorytransaction",
                    ),
                ),
                (
                    "item_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_batch.itembatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndentInventoryTransaction",
            fields=[
                (
                    "inventorytransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="inventory_transaction.inventorytransaction",
                    ),
                ),
                ("supplyOrderNo", models.CharField(max_length=20, unique=True)),
                ("supplyOrderDate", models.DateField()),
                ("dateOfDeliverty", models.DateField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                    ),
                ),
            ],
            bases=("inventory_transaction.inventorytransaction",),
        ),
    ]
