# Generated by Django 5.0.1 on 2024-02-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="inventory_transaction_id",
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
