# Generated by Django 5.0.1 on 2024-02-05 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0002_rename_dateofdeliverty_indentinventorytransaction_date_of_deliverty_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="indentinventorytransaction",
            old_name="date_of_deliverty",
            new_name="date_of_delivery",
        ),
    ]
