# Generated by Django 5.0.1 on 2024-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0002_inventorytransaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indentinventorytransaction",
            name="requested_quantity",
        ),
        migrations.AddField(
            model_name="indentinventorytransaction",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
