# Generated by Django 5.0.1 on 2024-02-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0003_rename_date_of_deliverty_indentinventorytransaction_date_of_delivery",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueItemInventoryTransaction",
            fields=[
                (
                    "inventorytransaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="inventory_transaction.inventorytransaction",
                    ),
                ),
                ("issue_to", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
            ],
            bases=("inventory_transaction.inventorytransaction",),
        ),
    ]
