# Generated by Django 5.0.1 on 2024-02-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0004_issueiteminventorytransaction"),
        ("organisation_section", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueiteminventorytransaction",
            name="item_receiver",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issueiteminventorytransaction",
            name="issue_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_to",
                to="organisation_section.organisactionsection",
            ),
        ),
    ]
