# Generated by Django 5.0.1 on 2024-01-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0004_alter_inventorytransaction_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indentinventorytransaction",
            name="quantity",
        ),
        migrations.AddField(
            model_name="inventorytransactionitem",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
