# Generated by Django 5.0.1 on 2024-01-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0005_remove_indentinventorytransaction_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransactionitem",
            name="inventory_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventorytransactionitem_set",
                to="inventory_transaction.inventorytransaction",
            ),
        ),
    ]
