# Generated by Django 5.0.1 on 2024-02-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0005_issueiteminventorytransaction_item_receiver_and_more",
        ),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemStockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("remarks", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="item.item"
                    ),
                ),
            ],
        ),
    ]
