# Generated by Django 5.0.1 on 2024-02-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "inventory_transaction",
            "0006_alter_inventorytransactionitem_inventory_transaction",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
