# Generated by Django 5.0.1 on 2024-02-07 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0007_alter_itemstockinfo_item"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemStockInfo",
        ),
    ]
