# Generated by Django 5.0.1 on 2024-02-10 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0008_delete_itemstockinfo"),
        ("item", "0004_alter_itemstockinfo_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransactionitem",
            name="item_stock_info",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="item.itemstockinfo",
            ),
            preserve_default=False,
        ),
    ]
