# Generated by Django 5.0.1 on 2024-02-10 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0009_inventorytransactionitem_item_stock_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorytransactionitem",
            name="item_stock_info",
        ),
    ]
