# Generated by Django 5.0.1 on 2024-02-10 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0010_remove_inventorytransactionitem_item_stock_info",
        ),
        ("item", "0006_delete_itemstockinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemStockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("remarks", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "inventory_transaction_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_stock_info",
                        to="inventory_transaction.inventorytransactionitem",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_stock_info",
                        to="item.item",
                    ),
                ),
            ],
        ),
    ]
