# Generated by Django 5.0.1 on 2024-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0011_itemstockinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inventorytransactionitem",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="itemstockinfo",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
