# Generated by Django 5.0.1 on 2024-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0012_inventorytransaction_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorytransaction",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="itemstockinfo",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RemoveField(
            model_name="inventorytransactionitem",
            name="active",
        ),
    ]
