# Generated by Django 5.0.1 on 2024-06-24 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "inventory_transaction_type",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("dispense", "Dispense"),
                            ("dispose", "Dispose"),
                            ("itemReturnToSupplier", "ItemReturnToSupplier"),
                            ("itemIssue", "ItemIssue"),
                            ("itemIssueReturn", "ItemIssueReturn"),
                            (
                                "itemturnReplacementFromSupplier",
                                "ItemturnReplacementFromSupplier",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "inventory_transaction_id",
                    models.CharField(editable=False, max_length=100),
                ),
                ("remarks", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransactionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.IntegerField()),
                (
                    "inventory_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transaction_item_set",
                        to="inventory_transaction.inventorytransaction",
                    ),
                ),
                (
                    "item_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.itembatch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemStockInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "inventory_transaction_type",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("dispense", "Dispense"),
                            ("dispose", "Dispose"),
                            ("itemReturnToSupplier", "ItemReturnToSupplier"),
                            ("itemIssue", "ItemIssue"),
                            ("itemIssueReturn", "ItemIssueReturn"),
                            (
                                "itemturnReplacementFromSupplier",
                                "ItemturnReplacementFromSupplier",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_batch_name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("item_quantity_in_stock", models.PositiveIntegerField()),
                ("item_batch_quantity_in_stock", models.PositiveIntegerField()),
                (
                    "inventory_transaction_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_batch_stock_info",
                        to="inventory_transaction.inventorytransactionitem",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_batch_stock_info",
                        to="item.item",
                    ),
                ),
                (
                    "item_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_batch_stock_info",
                        to="item.itembatch",
                    ),
                ),
            ],
        ),
    ]
