# Generated by Django 5.0.1 on 2024-05-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0001_initial"),
        ("item", "0002_item_contents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemstockinfo",
            name="item",
        ),
        migrations.AddField(
            model_name="itemstockinfo",
            name="item_batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_batch_stock_info",
                to="item.itembatch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemstockinfo",
            name="inventory_transaction_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_batch_stock_info",
                to="inventory_transaction.inventorytransactionitem",
            ),
        ),
    ]
