# Generated by Django 5.0.1 on 2024-02-18 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_transaction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorytransaction",
            old_name="date_time",
            new_name="date_and_time",
        ),
    ]
