# Generated by Django 5.0.1 on 2024-05-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0002_remove_itemstockinfo_item_itemstockinfo_item_batch_and_more",
        ),
        ("item", "0002_item_contents"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemstockinfo",
            name="inventory_transaction_type",
            field=models.CharField(
                choices=[
                    ("indent", "Indent"),
                    ("dispense", "Dispense"),
                    ("dispose", "Dispose"),
                    ("itemReturnToSupplier", "ItemReturnToSupplier"),
                    ("itemIssue", "ItemIssue"),
                    ("itemIssueReturn", "ItemIssueReturn"),
                    (
                        "itemturnReplacementFromSupplier",
                        "ItemturnReplacementFromSupplier",
                    ),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemstockinfo",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_batch_stock_info",
                to="item.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemstockinfo",
            name="item_batch_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemstockinfo",
            name="item_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
