# Generated by Django 5.0.1 on 2024-02-18 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0002_rename_date_time_inventorytransaction_date_and_time",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorytransaction",
            name="date_and_time",
        ),
    ]
