# Generated by Django 5.0.1 on 2024-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0003_itemstockinfo_inventory_transaction_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itemstockinfo",
            name="stock_in_hand",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
