# Generated by Django 5.0.1 on 2024-05-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_transaction",
            "0006_rename_quantity_in_hand_itemstockinfo_quantity_in_stock",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemstockinfo",
            old_name="quantity_in_stock",
            new_name="item_batch_quantity_in_stock",
        ),
        migrations.AddField(
            model_name="itemstockinfo",
            name="item_quantity_in_stock",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
